### Wypisujemy wszystkie silniki
GET http://localhost:8080/api/engines
Accept: application/json

### Wypisujemy wszystkie silniki elektryczne
GET http://localhost:8080/api/engines/electric
Accept: application/json

### Wypisujemy wszystkie silniki spalinowe
GET http://localhost:8080/api/engines/combustion
Accept: application/json

### Dodajemy nowy silnik elektryczny
POST http://localhost:8080/api/engines
Content-Type: application/json

{
  "type": "electric",
  "power": 3,
  "fuelType": "wow",
  "capacity": 23.32
}

### Update'ujemy silnik elektryczny znając ID
PUT http://localhost:8080/api/engines
Content-Type: application/json

{
  "id": 1,
  "type": "electric",
  "power": 15,
  "fuelType": "wow",
  "capacity": 23.32
}

### Usuwamy silnik po ID
DELETE http://localhost:8080/api/engines/1
Accept: application/json

### Wypisujemy wszystkie samochody
GET http://localhost:8080/api/cars
Accept: application/json

### Dodajemy nowy samochod
POST http://localhost:8080/api/cars
Content-Type: application/json

{
    "name": "Tesla Model S",
    "model": "wow",
    "color": "Red",
    "acceleration": 3.1,
    "transmission": "wow",
    "topSpeed": 250.5,
    "gasMileage": 0.0,
    "drivetrainType": "wow",
    "description": "Luxury electric sedan with high performance.",
    "bodyType": "wow",
    "price": 79999.99,
    "imagePath": "/images/tesla-model-s.jpg",
    "vinNumber": "dncdn",
    "productionYear": 1999
}

### Usuwamy samochod po ID
DELETE http://localhost:8080/api/cars/1
Accept: application/json

### Dodajemy silnik do samochodu po ich ID
PUT http://localhost:8080/api/cars/1/add-engine/1

### Update'ujemy samochód po jego ID
PUT http://localhost:8080/api/cars
Content-Type: application/json

{
    "id": 2,
    "name": "Tesla Model S",
    "model": "wow",
    "color": "Pink",
    "acceleration": 3.1,
    "transmission": "wow",
    "topSpeed": 250.5,
    "gasMileage": 0.0,
    "drivetrainType": "wow",
    "description": "Luxury electric sedan with high performance.",
    "bodyType": "wow",
    "price": 79999.99,
    "imagePath": "/images/tesla-model-s.jpg",
    "vinNumber": "dncdn",
    "productionYear": 1999
}

